filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
repositories:
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: dev
  url: http://chartmuseum-jx.34.123.102.163.nip.io/
releases:
- chart: jx3/jx-verify
  name: jx-verify
  namespace: jx-production
  values:
  - jx-values.yaml
- chart: dev/goodnode
  version: 0.0.1
  name: goodnode
  namespace: jx-production
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
